import pandas as pd

appNamesAndroid = [
    "Go Kinetic by Windstream",
    "My altafiber",
    "Spectrum Access: Enabled Media",
    "Cox",
    "My Verizon",
    "myCricket",
    "MyDISH",
    "T-Mobile",
    "Xfinity Mobile",
    "Spectrum News: Local Stories",
    "My Spectrum",
    "My Sprint",
    "Verizon My Fios",
    "My CenturyLink",
    "Visible mobile",
    "SpectrumU",
    "Spectrum TV",
    "myAT&T",
    "Spectrum SportsNet: Live Games",
    "MediacomConnect",
    "myMetro",
    "MyFrontier",
    "Xfinity",
    "Google Fiber",
    "My Viasat",
    "Armstrong",
    "Astound Mobile",
    "HughesNet Mobile",
    "HT My Account",
    "Midco My Account",
    "Optimum Support",
    "UScellular™ – My Account",
    "My SECTV",
    "Optimum TV",
    "Breezeline TV",
    "My Blue Ridge",
    "myBuckeye",
]

appNamesIOS = [
    "Go Kinetic by Windstream",
    "My altafiber",
    "Spectrum Access: Enabled Media",
    "Cox App",
    "My Verizon",
    "myCricket App",
    "MyDISH Account",
    "T-Mobile",
    "Xfinity Mobile",
    "Spectrum News: Local Stories",
    "My Spectrum",
    "My Sprint Mobile",
    "Verizon My Fios",
    "My CenturyLink",
    "Visible mobile",
    "SpectrumU",
    "Spectrum TV",
    "myAT&amp;T",
    "Spectrum SportsNet: Live Games",
    "MediacomConnect",
    "MyMetro",
    "MyFrontier",
    "Xfinity",
    "Google Fiber",
    "My Viasat",
    "Armstrong",
    "Astound Mobile",
    "HughesNet Mobile",
    "HT My Account",
    "Midco My Account",
    "Optimum Support",
    "UScellular™ – My Account",
    "SE Next powered by Tivo",
    "Optimum TV",
    "Breezeline TV",
    "My Blue Ridge",
    "myBuckeye",
]

mapping = [
    "GKW",
    "MAF",
    "SAEM",
    "CA",
    "MV",
    "MC",
    "MD",
    "TM",
    "XM",
    "SNLS",
    "MSA",
    "MSP",
    "VMF",
    "MCL",
    "VM",
    "SU",
    "STVA",
    "ATT",
    "SSLG",
    "MDCM",
    "MM",
    "MFR",
    "XF",
    "GFBR",
    "MVIA",
    "ARM",
    "ASTRCN",
    "HUGH",
    "HTMYA",
    "MIDCO",
    "OPTS",
    "USCELL",
    "SEC",
    "OPTTV",
    "BRE",
    "BLUER",
    "BUCK",
]


keyAndroid = pd.DataFrame({"App Name": appNamesAndroid, "Mapping": mapping})
keyIOS = pd.DataFrame({"App Name": appNamesIOS, "Mapping": mapping})
